---
name: CI Build
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  static-checks:
    name: "Pre-commit checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: "Run setup"
        run: python setup.py develop
      - name: "Install requirements"
        run: pip install -r requirements_dev.txt
      - uses: pre-commit/action@v1.0.1
